version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "torch"
      - dependency-name: "torchaudio"
      - dependency-name: "torchvision"
      - dependency-name: "torchcodec"
